name: SSH and Execute Build Script

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: self-hosted
    if: contains(fromJson('["ksikka"]'), github.event.pull_request.user.login)


    steps:
      - name: Execute build script via SSH
        run: |
          ssh axon 'sh buildbot/build_srun.sh ${{ github.event.pull_request.number }}'
