name: Run tests
on:
  workflow_dispatch:
  # to re-run status checks, mark PR as draft then ready_for_review.
  pull_request:
    types: [ready_for_review]
jobs:
  pytest-ubuntu:
    # For security, only run tests when authorized users trigger the request.
    if: ${{ github.actor == 'ksikka' || github.actor == 'themattinthehatt' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
          pip install fiftyone-db-ubuntu2204
      - name: Test with pytest
        run: |
          pytest
