# Run tests via Github Actions.
# The strategy is to do this manually, and on PR merge.
# Alternatively you can trigger this on every push or PR update,
# but that will consume a lot of resources unnecessarily.
name: Run tests
on:
  # Allow manually running from Github UI or API.
  workflow_dispatch:

  # Allow triggering from a merge queue.
  # We will not allow merging PRs that fail CI.
  # merge_group:
  #   types: [checks_requested]
  pull_request:
    types: [opened, reopened, ready_for_review]
jobs:
  build-linux:
    # Ships with python 3.10. Using it saves time installing it.
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          #        pip install -e ".[dev]"
          pip install fiftyone-db-ubuntu2204
          #- name: Test with pytest
          #run: |
          #pytest
